name: fib_flow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Zadanie 1
    
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Skonfigurowanie dockera + buildx
      - name: Buildx installation
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host
      # Instalacja QEMU 
      - name: QEMU installation
        uses: docker/setup-qemu-action@v2

      # Logowanie do Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Logowanie do GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_HUB_ACCESS_TOKEN }}

      # Wyodrębnienie metadanych
      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/fibcalc
            ghcr.io/${{ github.repository_owner }}/fibcalc
          # {{version}} = {{major}}.{{minor}}.{{patch}}
          tags: |
            type=ref,event=branch
            type=ref,prefix=pr-,event=pr
            type=semver,pattern={{version}}
      # Zbudowanie i wypchniecie obrazu na Dockerhub, GitHub Container Registry
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
          context: ./app
          file: ./app/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fibcalc:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fibcalc:cache,mode=max
